require('nvport').setup {
    theme = 'habamax',
    packs = {
        'https://github.com/neovim/nvim-lspconfig',
        'https://github.com/nvim-treesitter/nvim-treesitter',
        'https://github.com/stevearc/conform.nvim',
        'https://github.com/ibhagwan/fzf-lua',
        'https://github.com/nvim-lua/plenary.nvim',
        'https://github.com/mikavilpas/yazi.nvim',
        'https://github.com/NMAC427/guess-indent.nvim',
    },
    servers = {
        'lua_ls',
    },
    parsers = {
        'bash',
        'lua',
        'luadoc',
        'printf',
        'vim',
        'vimdoc',
        'nix',
        'markdown',
        'markdown_inline',
        'python',
        'query',
        'regex',
        'json',
    },
}
