return function(c)
    return {
        ColorColumn = { bg = c.base01 },
        Conceal = { fg = c.base1B, bg = c.base00 },
        CurSearch = { fg = c.base12, bg = c.base0Y },
        Cursor = { reverse = true },
        vCursor = { reverse = true },
        iCursor = { reverse = true },
        lCursor = { reverse = true },
        CursorIM = { reverse = true },
        CursorColumn = { bg = c.base01 },
        CursorLine = { bg = c.base01 },
        CursorLineNr = { fg = c.base12 },
        Debug = { fg = c.base0R },
        debugPC = { fg = c.base00, bg = c.base12 },
        debugBreakpoint = { fg = c.base00, bg = c.base02 },
        Directory = { fg = c.base1B },
        ErrorMsg = { fg = c.base1R, bold = true },
        EndOfBuffer = { fg = c.base10 },
        FloatBorder = { fg = c.base10, bg = c.base00 },
        FloatTitle = { fg = c.base10, bg = c.base00 },
        FloatFooter = { fg = c.base10, bg = c.base00 },
        Folded = { fg = c.base10, bg = c.base01 },
        FoldColumn = { fg = c.base10, bg = c.base00 },
        IncSearch = { fg = c.base00, bg = c.base0Y },
        LineNr = { fg = c.base10 },
        MatchParen = { fg = c.base12, bg = c.base11 },
        MoreMsg = { fg = c.base1B, bold = true },
        MsgSeparator = { fg = c.base0G, bg = c.base01, bold = true },
        NonText = { fg = c.base10 },
        Normal = { fg = c.base12, bg = c.base00 },
        NormalFloat = { fg = c.base12, bg = c.base00 },
        ModeMsg = { fg = c.base0G },
        Pmenu = { fg = c.base12, bg = c.base00 },
        PmenuSel = { fg = c.base0R, bg = c.base01 },
        PmenuSbar = { fg = c.base11, bg = c.base10 },
        PmenuThumb = { fg = c.base10, bg = c.base11 },
        Question = { fg = c.base0R },
        QuickFixLine = { fg = c.base1B, underline = true },
        Search = { fg = c.base12, bg = c.base0Y },
        SignColumn = { fg = c.base12, bg = c.base00 },
        SpecialKey = { fg = c.base10 },
        SpellBad = { fg = 'none', undercurl = true },
        SpellCap = { fg = 'none', undercurl = true },
        SpellLocal = { fg = 'none', undercurl = true },
        SpellRare = { fg = 'none', undercurl = true },
        StatusLine = { fg = c.base12, bg = c.base10 },
        StatusLineTerm = { fg = c.base12, bg = c.base01 },
        StatusLineNC = { fg = c.base10, bg = c.base00 },
        StatusLineTermNC = { fg = c.base10, bg = c.base01 },
        Substitute = { fg = c.base1Y, bg = c.base11 },
        TabLine = { fg = c.base12, bg = c.base01 },
        TabLineFill = { fg = c.base10, bg = c.base01 },
        TabLineSel = { fg = c.base00, bg = c.base12 },
        Terminal = { fg = c.base12, bg = c.base00 },
        ToolbarButton = { fg = c.base00, bg = c.base11 },
        ToolbarLine = { fg = c.base12 },
        Visual = { fg = c.base12, bg = c.base11 },
        VisualNOS = { fg = 'none', bg = c.base10, underline = true },
        WarningMsg = { fg = c.base1Y, bold = true },
        Whitespace = { fg = c.base10 },
        WildMenu = { fg = c.base00, bg = c.base1B },
        WinSeparator = { fg = c.base10 },
    }
end
