return function(c)
    return {
        Boolean = { fg = c.base0R, bold = true },
        Comment = { fg = c.base10, italic = true },
        Conditional = { fg = c.base0P },
        Constant = { fg = c.base0Y },
        Character = { fg = c.base0G },
        Define = { fg = c.base0P },
        Delimiter = { fg = c.base10 },
        Float = { link = 'Number' },
        Function = { fg = c.base1B },
        Identifier = { fg = c.base0C },
        Include = { fg = c.base1P },
        Keyword = { fg = c.base0P },
        Label = { fg = c.base0Y },
        Number = { fg = c.base0Y },
        Operator = { fg = c.base02 },
        PreProc = { fg = c.base0P },
        Repeat = { fg = c.base0P },
        Special = { fg = c.base1C },
        SpecialChar = { fg = c.base0C },
        Statement = { fg = c.base0P },
        StorageClass = { fg = c.base0Y },
        String = { fg = c.base0G },
        Structure = { fg = c.base0P },
        Tag = { fg = c.base0Y },
        Todo = { fg = c.base0Y, bg = c.base01 },
        Type = { fg = c.base1Y },
        Typedef = { fg = c.base1Y },
    }
end
